version: "3.9"

x-ruby: &ruby
  platform: linux/x86_64
  environment:
    - RAILS_ENV=development
    - TZ=America/Sao_Paulo
    - DATABASE_URL=postgresql://postgres:password@db:5432/municipe?encoding=utf8&pool=5&timeout=5000
  volumes:
    - bundle_cache:/bundle
    - .:/app
  depends_on:
    - db

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=America/Sao_Paulo
    ports:
      - 5432:5432

  guard:
    <<: *ruby
    build: .
    command: bundle exec guard --no-bundler-warning --no-interactions

  web:
    <<: *ruby
    build: .
    command: zsh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle_cache:
